### ISSUE TITLE
Exception thrown if you configure more than one sensor

### ISSUE THREAD

**Issue by psagrera** [Juniper/logstash-plugin-grpc-oc-keyvalue#3]
If I configure more than one sensor into the logstash config file, I'm getting the following error:

		input {
		    openconfig {
		        server => [ "10.102.187.188:50051" ]
		        sensors => ["/junos/system/linecard/cpu/memory/","/interfaces/"]
		        port => 50051
		        sampleFrequency => 10000 
		    }
		}

Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
15:10:27.394 [main] INFO  logstash.modules.scaffold - Initializing module {:module_name=>"netflow", :directory=>"/usr/share/logstash/modules/netflow/configuration"}
15:10:27.399 [main] INFO  logstash.modules.scaffold - Initializing module {:module_name=>"fb_apache", :directory=>"/usr/share/logstash/modules/fb_apache/configuration"}
15:10:27.437 [main] INFO  logstash.setting.writabledirectory - Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}
15:10:27.439 [main] INFO  logstash.setting.writabledirectory - Creating directory {:setting=>"path.dead_letter_queue", :path=>"/usr/share/logstash/data/dead_letter_queue"}
15:10:27.551 [LogStash::Runner] INFO  logstash.agent - No persistent UUID file found. Generating new UUID {:uuid=>"bc9fc732-df65-46bd-bde6-053daadcf42b", :path=>"/usr/share/logstash/data/uuid"}
15:10:29.701 [LogStash::Runner] INFO  logstash.inputs.openconfig - Using version 0.1.x input plugin 'openconfig'. This plugin isn't well supported by the community and likely has no maintainer.
15:10:31.118 [[main]-pipeline-manager] INFO  logstash.pipeline - Starting pipeline {"id"=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>1000}
15:10:31.419 [[main]-pipeline-manager] INFO  logstash.pipeline - Pipeline main started

Server: 10.102.187.188:50051
Port: 50051
Sensors: [/junos/system/linecard/cpu/memory/, /interfaces/]
CertFIle: 
15:10:32.608 [Api Webserver] INFO  logstash.agent - Successfully started Logstash API endpoint {:port=>9600}
Exception raised in OpenConfig: 
java.util.ConcurrentModificationException
Will retry in 10 seconds ...
Exception in thread "grpc-default-worker-ELG-1-3" java.lang.NoClassDefFoundError: io/netty/buffer/PoolArena$1
	at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:293)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:472)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:442)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:434)
	at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:291)
	at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:282)
	at io.netty.buffer.PoolThreadCache.free0(PoolThreadCache.java:255)
	at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:251)
	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:449)
	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:426)
	at io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:226)
	at io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:140)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.netty.buffer.PoolArena$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.jruby.util.JRubyClassLoader.findClass(JRubyClassLoader.java:221)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by psagrera** [comment]
Hi, 

Apparently, I've found a fix to avoid ConcurrentModificationException. 

                    synchronized(tr_record) <--- adding this line in OpenConfigTelemetryGrpcClient.java file
                    {
	                transform_record(record,device,sequence,sensor);
	                sequence = sequence + 1;
  
			         Iterator it = tr_record.entrySet().iterator();
			         while(it.hasNext()){
				        Map.Entry pair = (Map.Entry)it.next();
				        jruby.put("hash", pair.getValue());
				        jruby.put("q", queue);
	                	jruby.eval("print_function($hash, $q)");
                        it.remove();
			          }
                    }
